theme: jekyll-theme-dinky
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

title: Cro(k)nittlations
description: I the coolest
favicon: favicon.ico

markdown: GFM 

